export PATH=/usr/local/bin:$PATH

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
[[ -s "$HOME/.aliases" ]]         && source "$HOME/.aliases"

## Setting PATH for Python 3.4
## The orginal version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
#export PATH

## Setting PATH for Python 3.5
## The original version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
#export PATH
#export PATH="/usr/local/sbin:$PATH"
# export PATH="/usr/local/sbin:$PATH"
