export PATH=/usr/local/bin:$PATH

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
[[ -s "$HOME/.aliases" ]]         && source "$HOME/.aliases"
export PATH="/Applications/MacVim.app/Contents/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/MattAbrams/google-cloud-sdk/path.bash.inc' ]; then . '/Users/MattAbrams/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/MattAbrams/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/MattAbrams/google-cloud-sdk/completion.bash.inc'; fi
export PATH="/usr/local/sbin:$PATH"
