source "$HOME/.bash_scripts/separator_and_timestamp"
source "$HOME/.bash_scripts/bash_prompt"
source "$HOME/.bash_scripts/explain"
source "$HOME/.bash_scripts/zscript"

alias yaml2js="python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)'"
alias src="source ~/.bashrc"
alias pgrep="grep -irn -C2 --color"
alias tree="tree -CF"
alias vim='mvim -v'
alias tmux="tmux -2" # support 256 colors

# Github aliases for shorter commands

alias ga='git add'
alias gp='git push'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias glfl='git log --abbrev-commit --date=relative --graph -p'
alias glfm='git log --abbrev-commit --date=relative --graph --name-only -p'
alias glfs='git log --abbrev-commit --date=relative --graph'
alias gs='git status'
alias gd='git diff'
alias gm='git commit -m'
alias gam='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'

# source ~/.tmuxinator/tmuxinator.bash

export EDITOR=vim
export VISUAL=vim

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# set-vim-mode, important to keep before fzf
set -o vi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# heroku autocomplete setup
HEROKU_AC_BASH_SETUP_PATH=/Users/MattAbrams/Library/Caches/heroku/autocomplete/bash_setup && test -f $HEROKU_AC_BASH_SETUP_PATH && source $HEROKU_AC_BASH_SETUP_PATH;
# https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_shell_history.md
HISTCONTROL=ignoreboth

export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}'"
